on:
  push:
    branches:
    - main

name: Continuous Integration

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: dns-zone-test

    - name: Inspect tester image
      run: docker buildx imagetools inspect dns-zone-test

