on:
  push:
    branches:
    - main
  # https://crontab.guru/#12_21_*_*_0
  # At 21:12 on Sunday
  schedule:
    - cron: '12 21 * * 0'

name: Continuous Integration

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # This results in the local workspace having changed files
    - name: Fetch the latest hosts
      run: 'npm install && node build.js'

    - name: Run the tests
      run: ./test.sh

    # learnt from https://gist.github.com/anshumanb/16bf5e89354485f37912888d04d1be42
    # Also, commits pushed via the internal PAT don't trigger infinite Actions loops
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
    - name: Commit the results
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff-index --quiet HEAD || git commit -m "Automated update: $(date)"
        git push

