on:
  push:
    branches:
    - main

name: Continuous Integration

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run the tests
      run: ./test.sh

